### ISSUE TITLE
Search by Folder

### ISSUE THREAD

**Issue by jfrahm1987** [MikeShepard/KeePosh#3]
I would like the ability to search by folders in a KeePass database. To return a single user or all users in a Folder.

User Story:

Search for User "ServiceUser" in Folder "Service Accounts"
Return all information for account.
- Title
  -User Name
  -Password
  -URL
  -Notes

Or specify information to return.

**Comment by MikeShepard** [comment]
added -Folder parameter.

Will open a second issue for "specifying fields to return".
